apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: padvindersclub-nl
  namespace: redirector
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - padvindersclub.nl
    - www.padvindersclub.nl
    secretName: www-padvindersclub-nl
spec:
  ingressClassName: nginx
  rules:
    - host: padvindersclub.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 8080
    - host: www.padvindersclub.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 8080
